[versions]
accompanist-pager = "0.36.0"
accompanist-pager-indicators = "0.36.0"
agp = "8.13.1"
android-junit = "1.3.0"
appcompat = "1.7.1"
coil = "3.3.0"
compose = "1.9.5"
compose-activity = "1.12.0"
composeBom = "2025.11.01"
constraintLayout = "2.2.1"
constraintlayout-compose = "1.1.1"
coreKtx = "1.17.0"
espresso = "3.7.0"
flowlayout = "0.30.1"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
jetbrainsKotlinJvm = "2.2.21"
junit = "4.13.2"
jsonSerialization = "1.9.0"
kotlin = "2.2.21"
ksp = "2.2.10-2.0.2"
lifecycle-viewmodel-compose = "2.10.0"
lifecycleLivedataKtx = "2.10.0"
lifecycleRuntime = "2.10.0"
material = "1.13.0"
navigation = "2.9.6"
retrofit = "3.0.0"
roomVersion = "2.8.4"
serializationConverter = "1.0.0"
serialization = "2.2.21"

[libraries]
accompanist-flowlayout = { group = "ca.gosyer", name = "accompanist-flowlayout", version.ref = "flowlayout" }
android-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
android-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
android-compose-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
# Needed for createComposeRule(), but not for createAndroidComposeRule<YourActivity>()
android-compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
android-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
android-compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
android-compose-runtime = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose" }
android-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
android-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
android-compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
android-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
android-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
android-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
android-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntime" }
android-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
android-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
android-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "android-junit" }
# Compose also carries android-lifecycle-runtime with itself
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
google-accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist-pager" }
google-accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist-pager-indicators" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
kotlin-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "serializationConverter" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "jsonSerialization" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
test-junit = { group = "junit", name = "junit", version.ref = "junit" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }

hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

convention-application = { id = "com.adrienmandroid.composecv.application" }
convention-library = { id = "com.adrienmandroid.composecv.library" }
convention-compose-library = { id = "com.adrienmandroid.composecv.compose" }
convention-hilt-library = { id = "com.adrienmandroid.composecv.hilt" }
convention-retrofit-core-library = { id = "com.adrienmandroid.composecv.retrofit.core" }
convention-retrofit-api-library = { id = "com.adrienmandroid.composecv.retrofit.api" }
convention-room-library = { id = "com.adrienmandroid.composecv.room" }